language: bash

os:
  - windows

compiler: clang
before_script:
-cd c:/
-curl -o csound-windows_x64-6.11.0.zip "https://github.com/csound/csound/releases/download/6.11.0/csound-windows_x64-6.11.0.zip"
-dir
-7z x csound-windows_x64-6.11.0.zip -o"C:/Program Files"
-dir  
