os:
  - windows
  - osx

osx_image: xcode9.2

compiler: clang
before_script:
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    ls
    gem install xcpretty
    gem install xcpretty-travis-formatter
    git remote rm origin
    cd ..
    curl -L -o csound6.11.0-OSX-universal.dmg 'https://github.com/csound/csound/releases/download/6.11.0/csound6.11.0-OSX-universal.dmg'
    ls
    hdiutil attach csound6.11.0-OSX-universal.dmg
    cp -R /Volumes/Csound6.11.0/ Csound
    hdiutil detach /Volumes/Csound6.11.0/
    cd Csound
    sudo installer -pkg csound6.11.0-OSX-universal.pkg -target /
    sudo install_name_tool -id /Library/Frameworks/CsoundLib64.framework/CsoundLib64  /Library/Frameworks/CsoundLib64.framework/CsoundLib64
    cd /Users/travis/build/rorywalsh/opcode_sdk
  fi
  if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
    cd c:/
    choco install 7z
    powershell Start-FileDownload 'https://github.com/csound/csound/releases/download/6.11.0/csound-windows_x64-6.11.0.zip'
    7z.exe x csound-windows_x64-6.11.0.zip -o"C:/Program Files"
  fi

# script:
#   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
#     mkdir build
#     cd build
#     cmake ..
#     make -j4
#   fi